'use strict';
(() => {
  const reduced=matchMedia('(prefers-reduced-motion: reduce)');
  const header=document.querySelector('.header');const progress=document.querySelector('.reading-progress');let queued=false;
  function scrollState(){queued=false;header.classList.toggle('header-scrolled',scrollY>90);const distance=document.documentElement.scrollHeight-innerHeight;progress.style.transform=`scaleX(${distance>0?scrollY/distance:0})`;}
  addEventListener('scroll',()=>{if(!queued){queued=true;requestAnimationFrame(scrollState);}},{passive:true});scrollState();
  if(!reduced.matches){const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('reveal-complete');observer.unobserve(entry.target);}}),{threshold:.08});document.querySelectorAll('.intro-grid h2,.services-heading h2,.workshop-title h2,.people-text h2,.hyundai-copy h2,.reviews-intro h2,.location-top h2,.japan-gallery,.care-statement').forEach(node=>{node.classList.add('reveal-panel');observer.observe(node);});}
  const appointmentInfo=document.querySelector('.appointment-grid>div');
  const appointmentForm=document.querySelector('#appointment-form');
  if(appointmentForm&&!appointmentForm.querySelector('.form-head')){const head=document.createElement('div');head.className='form-head';head.innerHTML='<span>01 / DIAGNÓSTICO INICIAL</span><h3>Contanos qué está pasando.</h3><p>Cuanto más claro llega el caso, mejor preparamos la primera revisión.</p>';appointmentForm.prepend(head);}
  if(appointmentForm){const context=appointmentForm.querySelector('[name="contexto"]');if(context)context.closest('label')?.remove();const availability=appointmentForm.querySelector('[name="disponibilidad"]');if(availability&&!appointmentForm.querySelector('[name="prioridad"]')){const priority=document.createElement('label');priority.className='field-shell field-priority';priority.dataset.step='+';priority.innerHTML='<span>¿Necesitás una atención prioritaria?</span><select name="prioridad" aria-label="Prioridad de la consulta"><option value="Consulta coordinada">Consulta coordinada</option><option value="Urgente">Es urgente</option></select><small>Marcá urgente si el auto no puede esperar; recepción evalúa la prioridad.</small>';availability.closest('label')?.before(priority);}if(availability){const label=availability.closest('label');if(label){const title=label.querySelector('span');if(title)title.innerHTML='Disponibilidad para coordinar <b>/ Opcional</b>';availability.placeholder='Ej.: martes por la mañana';}}}
  const privacyNote=appointmentForm?.querySelector('.privacy-note');if(privacyNote)privacyNote.textContent='Se abre WhatsApp con tu consulta ordenada. Esta web no guarda tus datos.';
  if(appointmentInfo&&!appointmentInfo.querySelector('.appointment-photo')){const figure=document.createElement('figure');figure.className='appointment-photo';figure.innerHTML='<img src="assets/equipo-diagnostico.png" alt="Diagnóstico y planificación frente a los vehículos en MOTORLOZ"><figcaption><span>ATENCIÓN COORDINADA</span><b>Escuchamos el caso y ordenamos el próximo paso.</b></figcaption>';appointmentInfo.append(figure);}
  const arrivalImages=document.querySelectorAll('.arrival-photos figure img');
  if(arrivalImages[0]){arrivalImages[0].src='assets/local-aereo.png';arrivalImages[0].alt='Vista aérea del local de MOTORLOZ en Montevideo';}
  if(arrivalImages[1]){arrivalImages[1].src='assets/taller-panoramica.png';arrivalImages[1].alt='Interior amplio del taller MOTORLOZ';}
  const peopleTitle=document.querySelector('.people-text h2');if(peopleTitle)peopleTitle.innerHTML='Te escuchamos.<br>Entendemos<br><em>tu auto.</em>';
  const hyundaiCopy=document.querySelector('.hyundai-copy');if(hyundaiCopy&&!hyundaiCopy.querySelector('.hyundai-badge')){const badge=document.createElement('div');badge.className='hyundai-badge';badge.setAttribute('aria-label','Hyundai, servicio oficial');badge.innerHTML='<svg viewBox="0 0 62 30" aria-hidden="true"><ellipse cx="31" cy="15" rx="29" ry="12"></ellipse><path d="M20 8v14M42 8v14M20 15h22"></path></svg><span>HYUNDAI</span><i>SERVICIO OFICIAL</i>';hyundaiCopy.querySelector('.eyebrow')?.after(badge);}
  const peopleParagraphs=document.querySelectorAll('.people-text>p');if(peopleParagraphs[0])peopleParagraphs[0].textContent='Cada ruido, aviso o cambio en la respuesta del vehículo es información. El equipo la escucha, la ordena y te explica qué conviene revisar.';if(peopleParagraphs[1])peopleParagraphs[1].textContent='Experiencia multimarca, tecnología de diagnóstico y una atención cercana para que sepas qué se hizo y por qué.';
  const japanNote=document.querySelector('.japan-note');if(japanNote)japanNote.textContent='ESPECIALISTAS SUBARU · ATENCIÓN MULTIMARCA';
  const films=document.querySelector('.films-section');const workshopSection=document.querySelector('#mirada');if(films&&workshopSection)workshopSection.parentNode.insertBefore(films,workshopSection);
  if(!reduced.matches){const motionObserver=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('is-in');motionObserver.unobserve(entry.target);}}),{threshold:.1,rootMargin:'0px 0px -7%'});document.querySelectorAll('.precision-rail article,.service-list details,.film-card,.arrival-grid,.appointment-photo').forEach(node=>{node.classList.add('motion-item');motionObserver.observe(node);});document.querySelectorAll('.service-visual,.gallery-main,.gallery-secondary,.team-story,.hyundai-image,.google-review-card,.arrival-photos figure').forEach((node,index)=>{node.classList.add('scroll-reveal');node.style.setProperty('--reveal-delay',`${(index%3)*70}ms`);motionObserver.observe(node);});}
  const images=[['mecanica-subaru.png','Diagnóstico y mecánica general en MOTORLOZ'],['elevadores.png','Alineación y balanceo en el taller'],['subaru-taller.jpg','Revisión del tren delantero y la suspensión'],['equipo-diagnostico.png','Diagnóstico de sistemas eléctricos y electrónicos'],['toyota-frente.png','Revisión de ruedas y cubiertas'],['equipo-mecanica.png','Mantenimiento preventivo y cambio de aceite']];
  const image=document.querySelector('#service-image');let current=0,version=0;
  document.querySelectorAll('.service-list details').forEach((detail,index)=>{const figure=document.createElement('figure');figure.className='service-mobile-image';const mobileImage=document.createElement('img');mobileImage.src=`assets/${images[index][0]}`;mobileImage.alt=images[index][1];mobileImage.loading='lazy';mobileImage.decoding='async';figure.append(mobileImage);detail.querySelector('.service-body').prepend(figure);detail.addEventListener('toggle',async()=>{if(!detail.open||index===current)return;current=index;const request=++version;document.querySelector('#service-visual-index').textContent=`${String(index+1).padStart(2,'0')} / 06`;const next=new Image();next.src=`assets/${images[index][0]}`;try{await next.decode();}catch{return;}if(request!==version)return;image.src=next.src;image.alt=images[index][1];if(!reduced.matches)image.animate([{opacity:.3,filter:'blur(4px)',transform:'scale(1.018)'},{opacity:1,filter:'blur(0)',transform:'scale(1)'}],{duration:650,easing:'cubic-bezier(.2,.75,.25,1)'});});});
  const booking=document.querySelector('.floating-booking');let heroVisible=true,formVisible=false;const update=()=>booking.classList.toggle('is-visible',!heroVisible&&!formVisible);new IntersectionObserver(entries=>{for(const e of entries){if(e.target.id==='inicio')heroVisible=e.isIntersecting;if(e.target.id==='turno')formVisible=e.isIntersecting;}update();},{threshold:.1}).observe(document.querySelector('#inicio'));new IntersectionObserver(entries=>{formVisible=entries[0].isIntersecting;update();},{threshold:.1}).observe(document.querySelector('#turno'));
})();
