const text = 'Bien, te entiendo. Si el ruido empezó después de ese pozo, vamos por partes. ¿Lo sentís al doblar o también cuando vas derecho? Puede ser algo de la suspensión, pero hay que revisarlo para saber. Decime qué auto tenés y lo vemos juntos.';

const base = `Hablá en español rioplatense cotidiano de Montevideo, con voseo natural. Sos una persona del taller hablando cerca de un cliente, no un locutor ni un sistema automático. Soná cálido, claro y atento. Usá un ritmo de conversación real: uní las palabras dentro de cada idea, hacé pausas breves donde cambia el sentido y variá suavemente la entonación al preguntar. Evitá el tono recitado, las pausas iguales entre frases y cualquier acento forzado. Mantené la pronunciación española de los nombres y términos de mecánica. Si alguien describe un problema, escuchá con calma; no des un diagnóstico seguro. Decí solamente el texto proporcionado, una vez.`;

const definitions = [
  ['ash', 'Cálido y cercano', 'Medio y suave', 'Registro medio masculino y cálido, con una leve textura de voz. El inicio es una respuesta cercana a alguien que ya habló. Ritmo ágil de conversación; la pregunta sube apenas y el cierre es amable. Un asesor que escucha sin apurar.', 'Un tono medio y amable. La intención es conversar de cerca y escuchar.'],
  ['echo', 'Ágil y conversador', 'Medio y dinámico', 'Registro medio masculino, despierto y espontáneo. Ligá las frases como en una charla; cambiá el ritmo al pasar de escuchar a preguntar. Hacé una pausa corta tras vamos por partes. La pregunta es curiosa y el final invita a seguir conversando, con calidez.', 'Más ritmo y variación al preguntar. La intención es una charla espontánea.'],
  ['cedar', 'Sereno y atento', 'Grave y calmado', 'Registro grave masculino, próximo y sereno. Bien, te entiendo lleva empatía contenida, como si el cliente estuviera inquieto. Bajá ligeramente la intensidad al explicar la incertidumbre. Preguntá con interés real y cerrá con una seguridad tranquila, a velocidad normal.', 'Un tono grave con preocupación contenida y una explicación tranquila.'],
  ['ballad', 'Amable y liviano', 'Medio y luminoso', 'Registro medio masculino, liviano y accesible. Sonrisa muy leve en el cierre; el problema se toma en serio. Usá melodía conversacional suave y frases fluidas, sin solemnidad. La pregunta contrasta al doblar con cuando vas derecho y espera una respuesta.', 'Un tono más liviano y abierto. La intención es que dé confianza para preguntar.'],
  ['verse', 'Claro y didáctico', 'Medio y reflexivo', 'Registro medio masculino, concreto y reflexivo. Explicá como a alguien al lado del auto: claridad sin dar una clase. Pequeño cambio de intención antes de puede ser algo, marcando que es una posibilidad. Pregunta sencilla, vocales relajadas y cierre cálido, ritmo natural.', 'La explicación busca claridad, con pausas cortas y un tono reflexivo.'],
  ['onyx', 'Firme y de taller', 'Grave y firme', 'Registro grave masculino con presencia cotidiana. Evitá el bajo impostado de publicidad: la voz viene de una persona hablando normalmente en el taller. Ataques suaves, frases ligadas, pregunta atenta y final cercano. Ritmo vivo sin apuro, firmeza sin frialdad.', 'Un tono grave con más presencia. La intención es transmitir criterio sin solemnidad.']
];

module.exports = Object.freeze(Object.fromEntries(definitions.map(([voice, label, tone, direction, description], index) => [String(index + 1), Object.freeze({
  voice, label, tone, description, text, model: 'gpt-4o-mini-tts', instructions: `${base}\nTONALIDAD E INTERPRETACIÓN: ${direction}`
})])));
